package com.aifishing.strategy.domain;

public enum DataLimitationCode {
    WEATHER_UNAVAILABLE,
    WEATHER_OUT_OF_FORECAST_RANGE,
    WEATHER_FAILED,
    WATER_TEMPERATURE_UNAVAILABLE,
    BATHYMETRY_PARTIAL,
    BATHYMETRY_UNAVAILABLE,
    VEGETATION_DATA_UNAVAILABLE,
    BOTTOM_SUBSTRATE_UNAVAILABLE,
    TARGET_SPECIES_UNCONFIRMED,
    STRUCTURE_DATA_LOW_CONFIDENCE,
    STRUCTURE_NONE_AFTER_ANALYSIS,
    STRUCTURE_PIPELINE_NOT_READY,
    REGULATION_COVERAGE_PARTIAL,
    REGULATION_DATA_UNAVAILABLE,
    FISH_HABITAT_PARTIAL,
    FISH_HABITAT_UNAVAILABLE
}
