package com.aifishing.guidance.contracts;

public enum DecisionValidationCheck {
    ACTION_INCOMPATIBLE,
    HORIZON_COMMIT_INVALID,
    WAYPOINT_NOT_FOUND,
    WAYPOINT_NOT_NAVIGABLE,
    WAYPOINT_ID_INCONSISTENT,
    WAYPOINT_NOT_IN_SESSION,
    WAYPOINT_NOT_ON_LAKE,
    GPS_ACCURACY_UNACCEPTABLE,
    INSUFFICIENT_REMAINING_RANGE,
    INSUFFICIENT_RETURN_RESERVE,
    INSUFFICIENT_REMAINING_TIME,
    WEATHER_UNSAFE,
    NO_FISHING_ZONE,
    SCHEMA_INVALID,
    REQUIRED_DATA_MISSING,
    OPPORTUNITY_IN_COOLDOWN,
    MOVE_OSCILLATION
}
