package com.aifishing.guidance.contracts;

public enum GuidanceTrigger {
    USER_REQUEST,
    NO_BITE_THRESHOLD,
    FISH_ON,
    REPEATED_BITE_PATTERN,
    WAYPOINT_REACHED,
    PLAN_STEP_COMPLETED,
    SIGNIFICANT_WEATHER_CHANGE,
    SIGNIFICANT_LOCATION_CHANGE,
    CONSECUTIVE_FAILURE,
    SAFETY_STATE_CHANGED,
    ROUTE_DEVIATION,
    RETURN_RISK_CHANGED,
    USER_STARTED_AD_HOC_FISHING,
    USER_ENDED_AD_HOC_FISHING
}
