package com.aifishing.guidance.contracts;

public enum SessionEventType {
    SESSION_STARTED,
    GPS_UPDATED,
    GPS_ACCURACY_DEGRADED,
    WEATHER_UPDATED,
    WAYPOINT_ENTERED,
    WAYPOINT_LEFT,
    LURE_CHANGED,
    DEPTH_CHANGED,
    RETRIEVE_CHANGED,
    ADVICE_CREATED,
    ADVICE_ACCEPTED,
    ADVICE_REJECTED,
    ADVICE_ACKNOWLEDGED,
    USER_MOVED,
    BITE,
    FISH_ON,
    CATCH_CREATED,
    NO_BITE,
    PLAN_REPLANNED,
    SAFETY_ALERT,
    SESSION_PAUSED,
    SESSION_RESUMED,
    SESSION_COMPLETED,
    USER_STARTED_AD_HOC_FISHING,
    USER_ENDED_AD_HOC_FISHING
}
