package com.aifishing.planning.filter;

public enum RejectionReason {
    OUTSIDE_LAKE,
    ON_ISLAND,
    INVALID_GEOMETRY,
    INVALID_LOCATION,
    NO_WATER_POINT,
    REGULATION_WHOLE_AREA,
    REGULATION_PRIMARY_SPECIES,
    SHORE_INACCESSIBLE,
    BOAT_TRAVEL_UNREASONABLE,
    SAFETY_HARD_REJECT,
    DUPLICATE,
    STALE_OR_MISSING_FEATURE_SNAPSHOT
}
